import { MigrationInterface, QueryRunner } from "typeorm";

export class All1683472214438 implements MigrationInterface {
    name = 'All1683472214438'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "invitation_team" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "participantTeamId" integer NOT NULL, "tournamentId" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "type" character varying NOT NULL, CONSTRAINT "PK_e252ae8906b8e70c59c65e4dcbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1cb31a06a9a0cfc7124173ea5" ON "invitation_team" ("type") `);
        await queryRunner.query(`CREATE TABLE "participant_request" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "participantTeamId" integer NOT NULL, "tournamentId" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "userRequestId" integer NOT NULL, CONSTRAINT "PK_76ccba51d15bdd8b30ed9a33d8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "participant_invitation" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "participantTeamId" integer NOT NULL, "tournamentId" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "userInvitedId" integer NOT NULL, CONSTRAINT "PK_00f9a672103f68ab846f89290f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "referee" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "tournamentId" integer NOT NULL, CONSTRAINT "PK_e0f1d9028c5872562b234fae470" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "tournamentId" integer NOT NULL, CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT true, "tournamentId" integer NOT NULL, "seed" integer NOT NULL, CONSTRAINT "PK_65edadc946a7faf4b638d5e8885" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reschedule" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "schedule" character varying, "status" character varying NOT NULL DEFAULT 'request', "shortMessage" character varying NOT NULL, "matchId" integer NOT NULL, "playerId" integer, "superRefereeId" integer, "player1Id" integer, CONSTRAINT "PK_325e2759f6690dbf6a3513f0ad1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "super_referee" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "adminId" integer, "refereeId" integer, "ownerId" integer, CONSTRAINT "REL_59042d1f8b3bb23a023985445b" UNIQUE ("adminId"), CONSTRAINT "REL_3afc49878088c5cd1a11b2a8fa" UNIQUE ("refereeId"), CONSTRAINT "PK_97b0293765ed133c55f4e395345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lobby" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL DEFAULT 'pending', "schedule" character varying NOT NULL, "superRefereeId" integer NOT NULL, "qualifierId" integer NOT NULL, CONSTRAINT "PK_0d9e681a820740df03d4ba784bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "map" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "osuBeatmap" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'noMod', "numberOfType" integer NOT NULL DEFAULT '1', "beatmapsetId" integer NOT NULL, "beatmapId" integer NOT NULL, "mappoolId" integer NOT NULL, CONSTRAINT "PK_3b08de72489b3d4471b74516819" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qualifier_map" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "osuBeatmap" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'noMod', "numberOfType" integer NOT NULL DEFAULT '1', "beatmapsetId" integer NOT NULL, "beatmapId" integer NOT NULL, "mappoolId" integer NOT NULL, "qualifierId" integer NOT NULL, CONSTRAINT "PK_d039224f01cbd5e4eebe4401890" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "participant_map_score" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "rank" integer, "score" integer, "participantId" integer NOT NULL, "qualifierMapPlayedId" integer NOT NULL, "qualifierId" integer NOT NULL, "participantsHadScoredIds" integer array, CONSTRAINT "PK_cbdc8c8e77379e062cbe6f25889" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qualifier" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "tournamentId" integer NOT NULL, CONSTRAINT "REL_09fe08a12f3a7729063dc2de08" UNIQUE ("tournamentId"), CONSTRAINT "PK_88132922d07015ceeaa018fcbbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qualifier_participant" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT true, "seed" integer, "totalRank" integer, "totalScore" integer, "qualifierId" integer NOT NULL, CONSTRAINT "PK_325a782a33ab1c26f4e5c4a09d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."participant_type_enum" AS ENUM('individual', 'team')`);
        await queryRunner.query(`CREATE TABLE "participant" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT false, "tournamentId" integer NOT NULL, "type" "public"."participant_type_enum" NOT NULL, "userId" integer, "name" character varying, "captainId" integer, "qualifierParticipantId" integer, "playerId" integer, CONSTRAINT "REL_935b631bcd71b0a7d328be438f" UNIQUE ("qualifierParticipantId"), CONSTRAINT "REL_93e11e907b1503ff0ce88b261f" UNIQUE ("playerId"), CONSTRAINT "REL_eb0d6fbbc63d0799b5c3aa44b2" UNIQUE ("captainId"), CONSTRAINT "PK_64da4237f502041781ca15d4c41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_984c1b3f8ab33629d2aaad255f" ON "participant" ("type") `);
        await queryRunner.query(`CREATE TABLE "match" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "tournamentId" integer, "superRefereeId" integer, "firstTo" integer NOT NULL DEFAULT '7', "startDate" character varying, "rulesLobby" character varying, "matchesHistoryOsu" character varying, "player1Id" integer, "player2Id" integer, "winnerId" integer, "state" character varying NOT NULL DEFAULT 'pending', "identifier" integer, "player1PrevIdentifier" integer, "player2PrevIdentifier" integer, "round" integer NOT NULL, "player1Score" integer NOT NULL DEFAULT '0', "player2Score" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "draft" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "isPublic" boolean NOT NULL DEFAULT false, "isPublicable" boolean NOT NULL DEFAULT false, "details" character varying, "rangePlayerMax" integer, "rangePlayerMin" integer NOT NULL DEFAULT '1', "numbersPlayers" integer, "estimateStartDate" character varying, "teamNumberMax" integer NOT NULL DEFAULT '2', "teamNumberMin" integer NOT NULL DEFAULT '2', "type" character varying NOT NULL DEFAULT 'solo', "mode" character varying NOT NULL DEFAULT 'standard', "ownerId" integer NOT NULL, CONSTRAINT "PK_0b2b03d3f2c998450423648bc65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "isPublicable" boolean NOT NULL DEFAULT false, "isPublic" boolean NOT NULL DEFAULT false, "isFinished" boolean NOT NULL DEFAULT false, "isInBracketPhase" boolean NOT NULL DEFAULT false, "hasQualifier" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "startDate" character varying, "mode" character varying NOT NULL DEFAULT 'standard', "type" character varying NOT NULL DEFAULT 'solo', "description" character varying, "teamNumberMax" integer NOT NULL DEFAULT '2', "teamNumberMin" integer NOT NULL DEFAULT '2', "rangePlayerMax" integer, "rangePlayerMin" integer NOT NULL DEFAULT '1', "numbersPlayers" integer, "registrationEndDate" character varying, "registrationEnd" boolean NOT NULL DEFAULT false, "draftId" integer NOT NULL, "ownerId" integer NOT NULL, "winnerId" integer, CONSTRAINT "REL_254e4680f8329a5cc41109c019" UNIQUE ("draftId"), CONSTRAINT "PK_449f912ba2b62be003f0c22e767" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "osuId" integer NOT NULL, "username" character varying NOT NULL, "avatarUrl" character varying NOT NULL, "rank" integer NOT NULL, "discord" character varying, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mappooler" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "validate" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "tournamentId" integer NOT NULL, "mappoolId" integer, CONSTRAINT "PK_4cb240101b29fc34beb6e542558" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament_map" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "osuBeatmap" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'noMod', "numberOfType" integer NOT NULL DEFAULT '1', "beatmapsetId" integer NOT NULL, "beatmapId" integer NOT NULL, "mappoolId" integer NOT NULL, "tournamentId" integer NOT NULL, CONSTRAINT "PK_06e73b6fe342ca1fce8914a4921" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mappool" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "displayMappoolsSchedule" character varying, "isVisible" boolean NOT NULL DEFAULT false, "qualifierId" integer, "round" integer, "tournamentId" integer, "type" character varying NOT NULL, CONSTRAINT "REL_b76170818de9f8f76078aa8375" UNIQUE ("qualifierId"), CONSTRAINT "PK_25ed2ecdfd5aac2818a3b56be65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c418c1240d7ed14db5d34412b" ON "mappool" ("type") `);
        await queryRunner.query(`CREATE TABLE "credential" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "token" character varying NOT NULL, "refreshToken" character varying NOT NULL, CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lobby_participants_lobby_user" ("lobbyId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_6429d9735ac8af4a413855d9912" PRIMARY KEY ("lobbyId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fa6714e36cd3abe796f0406aaf" ON "lobby_participants_lobby_user" ("lobbyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_33aee1603fb36f1b25eafe0057" ON "lobby_participants_lobby_user" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user_participant_team_participant" ("userId" integer NOT NULL, "participantId" integer NOT NULL, CONSTRAINT "PK_cf2b2e8c13dbee6aa345ec2fb07" PRIMARY KEY ("userId", "participantId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d6ee3a5c4c567c89ecaca15b" ON "user_participant_team_participant" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c0cd949c21a45710e7010dfcd" ON "user_participant_team_participant" ("participantId") `);
        await queryRunner.query(`ALTER TABLE "invitation_team" ADD CONSTRAINT "FK_d138bf3d937a53544c84a05c1d5" FOREIGN KEY ("participantTeamId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_team" ADD CONSTRAINT "FK_fa1afc93fa324682768d80a95f2" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_request" ADD CONSTRAINT "FK_9c5722da022699f4d5264f23323" FOREIGN KEY ("participantTeamId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_request" ADD CONSTRAINT "FK_9b30fb292ac750e70e319ae27df" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_request" ADD CONSTRAINT "FK_e78b0ad5fe5c4a90f7a1defd440" FOREIGN KEY ("userRequestId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" ADD CONSTRAINT "FK_a9a9823859ae2172f72345d3626" FOREIGN KEY ("participantTeamId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" ADD CONSTRAINT "FK_6528cd4abb8228b7dada5642f7b" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" ADD CONSTRAINT "FK_65892183e71e74bb86c30e5cbaf" FOREIGN KEY ("userInvitedId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referee" ADD CONSTRAINT "FK_6697d3317bea5e6b6f1b091b20c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referee" ADD CONSTRAINT "FK_104023553b20492b9b146b76a4f" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin" ADD CONSTRAINT "FK_f8a889c4362d78f056960ca6dad" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin" ADD CONSTRAINT "FK_f0d5e3ea680a25ad26900deb919" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player" ADD CONSTRAINT "FK_7dbc7f7fbff9aa1a7da6d504fa6" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reschedule" ADD CONSTRAINT "FK_a988406b10a8facc1bc6c2d5661" FOREIGN KEY ("matchId") REFERENCES "match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reschedule" ADD CONSTRAINT "FK_8dee14761d450693200f243caa9" FOREIGN KEY ("player1Id") REFERENCES "player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reschedule" ADD CONSTRAINT "FK_baaa036ab87545517633bc638b0" FOREIGN KEY ("superRefereeId") REFERENCES "super_referee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "super_referee" ADD CONSTRAINT "FK_59042d1f8b3bb23a023985445b7" FOREIGN KEY ("adminId") REFERENCES "admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "super_referee" ADD CONSTRAINT "FK_3afc49878088c5cd1a11b2a8fa7" FOREIGN KEY ("refereeId") REFERENCES "referee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby" ADD CONSTRAINT "FK_d7cc08f33d10e97b70d50c23690" FOREIGN KEY ("superRefereeId") REFERENCES "super_referee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby" ADD CONSTRAINT "FK_cf23b8c52d18d5d1db950e6709c" FOREIGN KEY ("qualifierId") REFERENCES "qualifier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qualifier_map" ADD CONSTRAINT "FK_4fdabfd24134e9cd9bffd53cebb" FOREIGN KEY ("mappoolId") REFERENCES "mappool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" ADD CONSTRAINT "FK_bbcb2604f154830912ccff11ab6" FOREIGN KEY ("qualifierMapPlayedId") REFERENCES "qualifier_map"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" ADD CONSTRAINT "FK_6c381bc8f07303d677d8def325e" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" ADD CONSTRAINT "FK_4b78763ca88888eb9e731904bb8" FOREIGN KEY ("qualifierId") REFERENCES "qualifier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qualifier" ADD CONSTRAINT "FK_09fe08a12f3a7729063dc2de083" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qualifier_participant" ADD CONSTRAINT "FK_b052849e28f006e0aac4a3802df" FOREIGN KEY ("qualifierId") REFERENCES "qualifier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant" ADD CONSTRAINT "FK_99cba5cb409eb7e657295b474ba" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant" ADD CONSTRAINT "FK_935b631bcd71b0a7d328be438f0" FOREIGN KEY ("qualifierParticipantId") REFERENCES "qualifier_participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant" ADD CONSTRAINT "FK_93e11e907b1503ff0ce88b261f6" FOREIGN KEY ("playerId") REFERENCES "player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant" ADD CONSTRAINT "FK_b915e97dea27ffd1e40c8003b3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participant" ADD CONSTRAINT "FK_eb0d6fbbc63d0799b5c3aa44b26" FOREIGN KEY ("captainId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_b096f0c0ca94610b3e77128500c" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_cf2b82873792b5b0cf2224e7139" FOREIGN KEY ("superRefereeId") REFERENCES "super_referee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_7ecd38eb2baa65327de8fc6021f" FOREIGN KEY ("player1Id") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match" ADD CONSTRAINT "FK_d1f05e5fc2a7f92e29c8e3c8e0f" FOREIGN KEY ("player2Id") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft" ADD CONSTRAINT "FK_d015e602b44e29b24e083c07fb2" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament" ADD CONSTRAINT "FK_254e4680f8329a5cc41109c0195" FOREIGN KEY ("draftId") REFERENCES "draft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament" ADD CONSTRAINT "FK_9dbc398af9fdd807c8a7a105b15" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mappooler" ADD CONSTRAINT "FK_47610201720a1ce83c49572ad0f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mappooler" ADD CONSTRAINT "FK_9f7b83ab236b4ad8cb0403bc591" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mappooler" ADD CONSTRAINT "FK_9facf6a56573bd5aa5b22e2661a" FOREIGN KEY ("mappoolId") REFERENCES "mappool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_map" ADD CONSTRAINT "FK_a347cc5c025aad039c593abbe63" FOREIGN KEY ("mappoolId") REFERENCES "mappool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mappool" ADD CONSTRAINT "FK_b76170818de9f8f76078aa8375e" FOREIGN KEY ("qualifierId") REFERENCES "qualifier"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mappool" ADD CONSTRAINT "FK_fc12f197eeada184a57aabbfebe" FOREIGN KEY ("tournamentId") REFERENCES "tournament"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby_participants_lobby_user" ADD CONSTRAINT "FK_fa6714e36cd3abe796f0406aaf8" FOREIGN KEY ("lobbyId") REFERENCES "lobby"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lobby_participants_lobby_user" ADD CONSTRAINT "FK_33aee1603fb36f1b25eafe0057b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_participant_team_participant" ADD CONSTRAINT "FK_b5d6ee3a5c4c567c89ecaca15b2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_participant_team_participant" ADD CONSTRAINT "FK_4c0cd949c21a45710e7010dfcd1" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_participant_team_participant" DROP CONSTRAINT "FK_4c0cd949c21a45710e7010dfcd1"`);
        await queryRunner.query(`ALTER TABLE "user_participant_team_participant" DROP CONSTRAINT "FK_b5d6ee3a5c4c567c89ecaca15b2"`);
        await queryRunner.query(`ALTER TABLE "lobby_participants_lobby_user" DROP CONSTRAINT "FK_33aee1603fb36f1b25eafe0057b"`);
        await queryRunner.query(`ALTER TABLE "lobby_participants_lobby_user" DROP CONSTRAINT "FK_fa6714e36cd3abe796f0406aaf8"`);
        await queryRunner.query(`ALTER TABLE "mappool" DROP CONSTRAINT "FK_fc12f197eeada184a57aabbfebe"`);
        await queryRunner.query(`ALTER TABLE "mappool" DROP CONSTRAINT "FK_b76170818de9f8f76078aa8375e"`);
        await queryRunner.query(`ALTER TABLE "tournament_map" DROP CONSTRAINT "FK_a347cc5c025aad039c593abbe63"`);
        await queryRunner.query(`ALTER TABLE "mappooler" DROP CONSTRAINT "FK_9facf6a56573bd5aa5b22e2661a"`);
        await queryRunner.query(`ALTER TABLE "mappooler" DROP CONSTRAINT "FK_9f7b83ab236b4ad8cb0403bc591"`);
        await queryRunner.query(`ALTER TABLE "mappooler" DROP CONSTRAINT "FK_47610201720a1ce83c49572ad0f"`);
        await queryRunner.query(`ALTER TABLE "tournament" DROP CONSTRAINT "FK_9dbc398af9fdd807c8a7a105b15"`);
        await queryRunner.query(`ALTER TABLE "tournament" DROP CONSTRAINT "FK_254e4680f8329a5cc41109c0195"`);
        await queryRunner.query(`ALTER TABLE "draft" DROP CONSTRAINT "FK_d015e602b44e29b24e083c07fb2"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_d1f05e5fc2a7f92e29c8e3c8e0f"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_7ecd38eb2baa65327de8fc6021f"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_cf2b82873792b5b0cf2224e7139"`);
        await queryRunner.query(`ALTER TABLE "match" DROP CONSTRAINT "FK_b096f0c0ca94610b3e77128500c"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP CONSTRAINT "FK_eb0d6fbbc63d0799b5c3aa44b26"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP CONSTRAINT "FK_b915e97dea27ffd1e40c8003b3b"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP CONSTRAINT "FK_93e11e907b1503ff0ce88b261f6"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP CONSTRAINT "FK_935b631bcd71b0a7d328be438f0"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP CONSTRAINT "FK_99cba5cb409eb7e657295b474ba"`);
        await queryRunner.query(`ALTER TABLE "qualifier_participant" DROP CONSTRAINT "FK_b052849e28f006e0aac4a3802df"`);
        await queryRunner.query(`ALTER TABLE "qualifier" DROP CONSTRAINT "FK_09fe08a12f3a7729063dc2de083"`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" DROP CONSTRAINT "FK_4b78763ca88888eb9e731904bb8"`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" DROP CONSTRAINT "FK_6c381bc8f07303d677d8def325e"`);
        await queryRunner.query(`ALTER TABLE "participant_map_score" DROP CONSTRAINT "FK_bbcb2604f154830912ccff11ab6"`);
        await queryRunner.query(`ALTER TABLE "qualifier_map" DROP CONSTRAINT "FK_4fdabfd24134e9cd9bffd53cebb"`);
        await queryRunner.query(`ALTER TABLE "lobby" DROP CONSTRAINT "FK_cf23b8c52d18d5d1db950e6709c"`);
        await queryRunner.query(`ALTER TABLE "lobby" DROP CONSTRAINT "FK_d7cc08f33d10e97b70d50c23690"`);
        await queryRunner.query(`ALTER TABLE "super_referee" DROP CONSTRAINT "FK_3afc49878088c5cd1a11b2a8fa7"`);
        await queryRunner.query(`ALTER TABLE "super_referee" DROP CONSTRAINT "FK_59042d1f8b3bb23a023985445b7"`);
        await queryRunner.query(`ALTER TABLE "reschedule" DROP CONSTRAINT "FK_baaa036ab87545517633bc638b0"`);
        await queryRunner.query(`ALTER TABLE "reschedule" DROP CONSTRAINT "FK_8dee14761d450693200f243caa9"`);
        await queryRunner.query(`ALTER TABLE "reschedule" DROP CONSTRAINT "FK_a988406b10a8facc1bc6c2d5661"`);
        await queryRunner.query(`ALTER TABLE "player" DROP CONSTRAINT "FK_7dbc7f7fbff9aa1a7da6d504fa6"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP CONSTRAINT "FK_f0d5e3ea680a25ad26900deb919"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP CONSTRAINT "FK_f8a889c4362d78f056960ca6dad"`);
        await queryRunner.query(`ALTER TABLE "referee" DROP CONSTRAINT "FK_104023553b20492b9b146b76a4f"`);
        await queryRunner.query(`ALTER TABLE "referee" DROP CONSTRAINT "FK_6697d3317bea5e6b6f1b091b20c"`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" DROP CONSTRAINT "FK_65892183e71e74bb86c30e5cbaf"`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" DROP CONSTRAINT "FK_6528cd4abb8228b7dada5642f7b"`);
        await queryRunner.query(`ALTER TABLE "participant_invitation" DROP CONSTRAINT "FK_a9a9823859ae2172f72345d3626"`);
        await queryRunner.query(`ALTER TABLE "participant_request" DROP CONSTRAINT "FK_e78b0ad5fe5c4a90f7a1defd440"`);
        await queryRunner.query(`ALTER TABLE "participant_request" DROP CONSTRAINT "FK_9b30fb292ac750e70e319ae27df"`);
        await queryRunner.query(`ALTER TABLE "participant_request" DROP CONSTRAINT "FK_9c5722da022699f4d5264f23323"`);
        await queryRunner.query(`ALTER TABLE "invitation_team" DROP CONSTRAINT "FK_fa1afc93fa324682768d80a95f2"`);
        await queryRunner.query(`ALTER TABLE "invitation_team" DROP CONSTRAINT "FK_d138bf3d937a53544c84a05c1d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c0cd949c21a45710e7010dfcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5d6ee3a5c4c567c89ecaca15b"`);
        await queryRunner.query(`DROP TABLE "user_participant_team_participant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33aee1603fb36f1b25eafe0057"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa6714e36cd3abe796f0406aaf"`);
        await queryRunner.query(`DROP TABLE "lobby_participants_lobby_user"`);
        await queryRunner.query(`DROP TABLE "credential"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c418c1240d7ed14db5d34412b"`);
        await queryRunner.query(`DROP TABLE "mappool"`);
        await queryRunner.query(`DROP TABLE "tournament_map"`);
        await queryRunner.query(`DROP TABLE "mappooler"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "tournament"`);
        await queryRunner.query(`DROP TABLE "draft"`);
        await queryRunner.query(`DROP TABLE "match"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_984c1b3f8ab33629d2aaad255f"`);
        await queryRunner.query(`DROP TABLE "participant"`);
        await queryRunner.query(`DROP TYPE "public"."participant_type_enum"`);
        await queryRunner.query(`DROP TABLE "qualifier_participant"`);
        await queryRunner.query(`DROP TABLE "qualifier"`);
        await queryRunner.query(`DROP TABLE "participant_map_score"`);
        await queryRunner.query(`DROP TABLE "qualifier_map"`);
        await queryRunner.query(`DROP TABLE "map"`);
        await queryRunner.query(`DROP TABLE "lobby"`);
        await queryRunner.query(`DROP TABLE "super_referee"`);
        await queryRunner.query(`DROP TABLE "reschedule"`);
        await queryRunner.query(`DROP TABLE "player"`);
        await queryRunner.query(`DROP TABLE "admin"`);
        await queryRunner.query(`DROP TABLE "referee"`);
        await queryRunner.query(`DROP TABLE "participant_invitation"`);
        await queryRunner.query(`DROP TABLE "participant_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1cb31a06a9a0cfc7124173ea5"`);
        await queryRunner.query(`DROP TABLE "invitation_team"`);
    }

}
